repository_type: pipeline

nf_core_version: 3.3.2

lint: {}

template:
  org: nf-core
  name: rnaexome
  description: Targeted RNA-Seq (RNA Exome) Alignment & Gene Counts
  author: Chris Winnington github.com/WinniCode
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - gpu
  is_nfcore: true
